version: "3.9"

services:
  web:
    build: .
    user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-1350}
    volumes:
      - "./app:/usr/src/app"
    ports:
      - "1350:3000"